language: generic
sudo: require
services:
    - docker
before_install:
    - docker build -t nathzi1505/travis -f Dockerfile.dev .
script: 
    - docker run -e CI=true nathzi1505/travis npm run test
deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-tutorial-react"
    env: "DockerTutorialReact-env"
    bucket_name: "elasticbeanstalk-ap-south-1-994437792464"
    bucket_path: "docker-tutorial-react"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key:
        secure: "$AWS_SECRET_KEY"